---
title: "Overnight2018SolvingAnalysis"
author: "Kristin"
date: "December 28, 2018"
output: html_document
---

```{r}
###Notes to self:
#1) Add data cleaning script first (need to correct for puzzle that was solved in the evening after moving on to the next puzzle)


#2) Need to format tables better... something to do with the kable function in knitr?
    #After much struggle (kable was producing a blank screen) I got the kable() function to work by:
    #1. installing the latest version of RStudio and 2. making sure I was using dplyr::summarize function
    #Also adding the kableExtra package gives additional simple formatting options

#3) There is apparently a way to cache things so that knitting doesn't take as long (reading in the data every time is a hassle)
    #seems like I just need to add the option "cache = TRUE" to a code chunk and it will cache instead of     #re-loading each time -- will need to be careful if it does change though and needs to be reloaded


#Useful Resources#
#https://rmarkdown.rstudio.com/lesson-7.html
#https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf
#https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf

```



```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plyr) #pre-emptively attaching plyr so it doesn't overwrite dplyr when loaded in the read script
library(dplyr)
library(knitr)
library(kableExtra)
library(tidyr)
library(ggplot2)

```



```{r myfunctions, include = FALSE}

createAverageRow <- function(df){
  
  #creates a row average at the end of the data frame and returns the updated data frame
  #assumes the first column is some sort of identifier/named column and therefore not meant to be averaged
  
  nrow <- nrow(df)
  ncol <- ncol(df)
  df[nrow+1,1] <- "Average"
  df[nrow+1,2:ncol] <- colMeans(df[,2:ncol], na.rm=TRUE) 
  
  return(df)
  
}

showNiceTable <- function(df, mycaption, fn = NA){
  
  if(is.na(fn)){
    
    #no footnote
    kable(df, digits = 2, align = 'c', caption = mycaption) %>%
      kable_styling("striped", full_width = FALSE, position = "left")
    
  }else{
  
    #yes footnote
    kable(df, digits = 2, align = 'c', caption = mycaption) %>%
      kable_styling("striped", full_width = FALSE, position = "left") %>%
      footnote(general = fn)
  }  
  
}


```

# Solving Analysis for Evening and Morning Data


```{r preprocessing, include=FALSE, cache=TRUE}
source("Overnight2018ReadPresentationData.R")
source("Overnight2018CleanEveningData.R")
source("Overnight2018CleanMorningData.R")

#Run to reference raw data if necessary, also re-creates the rawdata_compiled output csv files for use in the
#cleaning scripts. Note this takes several seconds to minutes to run the first time the script is launched then it iscached for future use in that R session
rawData <- Overnight2018ReadPresentationData() 

```

```{r, include = FALSE}

#create and clean the evening and morning solving data
EData <- Overnight2018CleanEveningData()
MData <- Overnight2018CleanMorningData()

#adjust columns
EData$WarmthRatingResp <- as.numeric(EData$WarmthRatingResp)
MData$WarmthRatingResp <- as.numeric(MData$WarmthRatingResp)
MData$FairnessRatingResp <- as.numeric(MData$FairnessRatingResp)

#exclusions
MData <- subset(MData, TrialStatus != "exclude-solvedlastnight")

```


## Solution Rates by Subject

### Evening

```{r results = 'asis', echo = FALSE}

#Overall solving
e_propsolv <- EData %>%
  group_by(SID) %>%
  summarise(Proportion_Solved = mean(Solved))

e_propsolv <- createAverageRow(e_propsolv)

showNiceTable(e_propsolv, "Evening Solving Rates")

#By insight and analysis
e_propsolv_ia <- EData %>%
  group_by(SID,InsightorAnalysisResp) %>%
  tally() %>%
  spread(InsightorAnalysisResp, n)
e_propsolv_ia[is.na(e_propsolv_ia)] <- 0

e_propsolv_ia <- createAverageRow(e_propsolv_ia)

showNiceTable(e_propsolv_ia, "Evening Solving Rates by Insight and Analysis")



```

### Morning

```{r, echo = FALSE}

#Overall
m_propsolv <- MData %>%
  group_by(SID) %>%
  summarise(Proportion_Solved = mean(Solved))

m_propsolv <- createAverageRow(m_propsolv) #add average row


showNiceTable(m_propsolv, "Morning Solving Rates") 

#By Cued Status
m_propsolv_CU <- MData %>%
  dplyr::group_by(SID,CuedStatus) %>%
  dplyr::summarise(ProportionSolved = mean(Solved)) %>%
  spread(CuedStatus, ProportionSolved) %>%
  mutate(CueingEffect = C - U)

m_propsolv_CU <- createAverageRow(m_propsolv_CU) #add average row

showNiceTable(m_propsolv_CU, "Morning Solving Rates by Cueing")

#By Insight and Analysis
m_propsolv_CU_ia <- MData %>%
  group_by(SID,CuedStatus,InsightorAnalysisResp) %>%
  count() %>%
  ungroup() %>%
  mutate(CUIA = paste(CuedStatus, InsightorAnalysisResp, sep = "_")) %>%
  select(-CuedStatus, -InsightorAnalysisResp) %>%
  spread(CUIA, n)
m_propsolv_CU_ia[is.na(m_propsolv_CU_ia)] <- 0


```

## Evening Closeness & Stuckedness by Subjct

```{r}
#create dataset for unsolved data only (the ones that have closeness and fixation ratings)
e_unsolv <- subset(EData, TrialStatus == "unsolved")


#Fixation Ratings
e_fixstat <- e_unsolv %>%
  group_by(SID,FixationRatingResp) %>%
  tally() %>%
  spread(FixationRatingResp,n) %>%
  mutate(Total = sum(stillworking,stuck)) %>%
  mutate(Proportion_Stuck = stuck/Total)

e_fixstat <- createAverageRow(e_fixstat)

showNiceTable(e_fixstat, "Evening Stuckedness Ratings by Subject")

#Closeness Ratings
e_close <- e_unsolv %>%
  group_by(SID) %>%
  summarize(Mean_Closeness = mean(WarmthRatingResp, na.rm = TRUE))

e_close <- createAverageRow(e_close)

showNiceTable(e_close, "Evening Closeness Ratings by Subject")


#Average Closeness Ratings for Two Categories of Stuckedness
e_fixclose <- e_unsolv %>%
  group_by(SID, FixationRatingResp) %>%
  summarise(close = mean(WarmthRatingResp, na.rm = TRUE)) %>%
  spread(FixationRatingResp, close)

e_fixclose <- createAverageRow(e_fixclose)

showNiceTable(e_fixclose, "Evening Closeness Ratings by Subject & Stuckedness")


```

## Evening Closeness & Stuckedness by Puzzle Type

```{r}
#Fixation Ratings
e_fixstat_puz <- e_unsolv %>%
  group_by(ProblemType, FixationRatingResp) %>%
  tally() %>%
  spread(FixationRatingResp,n) %>%
  mutate(Total = sum(stillworking,stuck)) %>%
  mutate(Proportion_Stuck = stuck/Total)

e_fixstat_puz <- createAverageRow(e_fixstat_puz)

showNiceTable(e_fixstat_puz, "Evening Stuckedness Ratings by Puzzle Type")

#Closeness Ratings
e_close_puz <- e_unsolv %>%
  group_by(ProblemType) %>%
  summarize(Mean_Closeness = mean(WarmthRatingResp))

e_close_puz <- createAverageRow(e_close_puz)

showNiceTable(e_close_puz, "Evening Closeness Ratings by Subject")


```

## Morning Closeness & Solution Goodness by Subject

```{r, message = FALSE}

#Closness Ratings

#Unsolved puzzles only for closeness
m_unsolv <- subset(MData, TrialStatus == "unsolved")

#Closeness Ratings by CuedStatus and Overall
m_close <- m_unsolv %>%
  group_by(SID, CuedStatus) %>%
  summarize(Mean_Closeness = mean(WarmthRatingResp)) %>%
  spread(CuedStatus, Mean_Closeness) %>%
  ungroup()
#add overall column
o <- m_unsolv %>%
  group_by(SID) %>%
  summarize(Overall = mean(WarmthRatingResp))
m_close <- left_join(m_close,o)

m_close <- createAverageRow(m_close)

showNiceTable(m_close, "Morning Closeness Ratings by CuedStatus & Subject")


#Solution Goodness
m_goodsoln <- MData %>%
  group_by(SID,TrialStatus) %>%
  summarize(SolutionGoodness = mean(FairnessRatingResp, na.rm = TRUE)) %>%
  spread(TrialStatus, SolutionGoodness) %>%
  ungroup()
#add overall column
o <- MData %>%
  group_by(SID) %>%
  summarize(Overall = mean(FairnessRatingResp, na.rm = TRUE))
m_goodsoln <- left_join(m_goodsoln,o)

m_goodsoln <- createAverageRow(m_goodsoln)

showNiceTable(m_goodsoln, "Morning Solution Goodness Ratings by Solution Status & Subject")


```





## Memory Rates by Subject

### Evening

##### Evening Overall

```{r}

source("Overnight2018CleanEveningMemory.R")

eMem <- Overnight2018CleanEveningMemory()

#Memory for Each Round and Overall
e_psmem <- eMem %>%
  group_by(SID,Round) %>%
  summarise(Proportion_Recalled = mean(PSRecallAcc)) %>%
  spread(Round, Proportion_Recalled) %>%
  ungroup() %>%
  mutate(Average = rowMeans(.[,2:5])) #gets the row mean

e_psmem <- createAverageRow(e_psmem)

showNiceTable(e_psmem, "Evening Puzzle-Sound Memory by Round")

```

##### Evening by Session

```{r}
#Memory for Each Round by Session

e_psmem_bysess <- eMem %>%
  group_by(SID,Session,Round) %>%
  summarise(Proportion_Recalled = mean(PSRecallAcc))


#Graph

e_psmem_bysess$SID <- as.factor(e_psmem_bysess$SID)
e_psmem_bysess$Session <- as.factor(e_psmem_bysess$Session)
e_psmem_bysess$Round <- as.factor(e_psmem_bysess$Round)

ggplot(e_psmem_bysess, aes(x = Round, y = Proportion_Recalled, group = SID)) +
  theme_bw() +
  geom_point(aes(color = SID)) +
  geom_line(aes(color = SID)) +
  facet_grid(.~ Session)

#Overall Averages
e_psmem_bysess2 <- e_psmem_bysess %>%
  group_by(Session, Round) %>%
  summarize(Proportion_Recalled = mean(Proportion_Recalled)) %>%
  spread(Round, Proportion_Recalled) %>%
  ungroup() %>%
  mutate(Average = rowMeans(.[,2:5])) #gets the row mean

showNiceTable(e_psmem_bysess2, "Evening Memory by Round and Session")

```

### Morning

##### Morning Overall & By Session
```{r}

source("Overnight2018CleanMorningMemory.R")

mMem <- Overnight2018CleanMorningMemory()

#Puzzle-Sound Recall Memory by Session and Overall
m_psmem <- mMem %>%
  group_by(SID,Session) %>%
  summarise(Proportion_Recalled = mean(PSRecallAcc, na.rm=TRUE)) %>%
  spread(Session, Proportion_Recalled) %>%
  ungroup() %>%
  mutate(Average = rowMeans(.[,2:3]))

m_psmem <- createAverageRow(m_psmem)

showNiceTable(m_psmem, "Morning Puzzle-Sound Recall Memory by Session", fn = "e1 and e2 are actually m1 and m2")


#Puzzle-Sound Recognition Memory by Session and Overall
m_psrecog <- mMem %>%
  group_by(SID,Session) %>%
  summarise(Proportion_Recognized = mean(RecognitionAcc, na.rm=TRUE)) %>%
  spread(Session, Proportion_Recognized) %>%
  ungroup() %>%
  mutate(Average = rowMeans(.[,2:3]))

m_psrecog <- createAverageRow(m_psrecog)

showNiceTable(m_psrecog, "Morning Puzzle-Sound Recognition Memory by Session", fn = "e1 and e2 are actually m1 and m2 \n For the first four participants only 6/8 responses were recorded")

```

